### ISSUE TITLE
Reminder: Merge NMOS tags PR with elevation of BCP

### ISSUE THREAD

**Issue by JamesGibo** [AMWA-TV/nmos-certificate-provisioning#19]
https://github.com/AMWA-TV/nmos-parameter-registers/pull/20

**Comment by garethsb** [comment]
Good reminder. Also a slew of changes to references which are currently to `v1.0-dev`

**Comment by peterbrightwell** [comment]
Merged yesterday.  Will also tweak the reference once v1.0.0 release is made.
