### ISSUE TITLE
Base64 encoding pattern used by EST servers

### ISSUE THREAD

**Issue by prince-chrismc** [AMWA-TV/nmos-certificate-provisioning#3]
In the current Virtual Workshop, many vendors noticed the [OpenXPKI Server](https://github.com/openxpki/openxpki) and [Cisco Server](https://github.com/cisco/libest) had an interoperability issue.

- OpenXPKI does _not_ have any newlines `\n`
- Cisco follows the block newline encoding scheme

There may need to be clarification for EST servers to follow one or for clients to support both. Should there be an identifier for clients to know which?

**Comment by NEOAdvancedTechnology** [comment]
Is the Cisco implementation more technically correct?   If so, should we make an issue and/or PR to OpekXPKI?

**Comment by JamesGibo** [comment]
From a quick bit of research both are valid, the newline encoding scheme was created for clients that could not handle long lines.
I feel like any NMOS clients should be able to handle long lines and therefore the client should be responsible for being able to detect and decode both styles independently of the NMOS spec.

**Comment by prince-chrismc** [comment]
In that case, I think we just need some language in the BCP for clients to support both.
